### ISSUE TITLE
[Feature] Option to change the text for the buttons

### ISSUE THREAD

**Issue by Gabb1995** [lsqlabs/ngx-guided-tour#20]
I have a language picker and would like to have the guide both in French and English. Right now I'm using ngx-translate to translate the whole project. It would be nice if we could enter the exact string for each button (next, skip, back).

**Comment by RobertCMusk** [comment]
We do not have translations on our short term roadmap, but we may do it later this year. We do welcome PRs if anyone else would like to tackle it though!

**Comment by RobertCMusk** [comment]
version 1.1.5 should contain your changes
