### ISSUE TITLE
Errors with Angular Universal

### ISSUE THREAD

**Issue by attilaorosz** [lsqlabs/ngx-guided-tour#25]
Hi,

Currently there is an error thrown in GuidedTourService while using SSR because of the referenced window object in the constructor.

Thanks in advance,
Attila

**Comment by jcroldan** [comment]
Hi, @attilaorosz , have you found a solution? I'm having the same problem with bazel.

Thanks in advance.
J. Carlos.

**Comment by RobertCMusk** [comment]
@attilaorosz I noticed that you forked our project and committed a potential fix ( https://github.com/attilaorosz/ngx-guided-tour/commit/b074db6a066acc46cee967002c16c4944c4f87e2 ) . Did that work? We do not use Angular Universal so we would not be able to test it throughly.

You more than welcome to open a PR  if you want it in our project soon so you dont have to stay on a fork, but I am going to open an internal ticket on our team so hopefully we can add that code and resolve it for everyone.

**Comment by attilaorosz** [comment]
@RobertCMusk @jcroldan  My solution was just a temporary fix. Unfortunately the window and document globals (which are not available in SSR) are referenced throughout the library. I can prepare a PR tomorrow.

**Comment by attilaorosz** [comment]
Submitted PR #37

**Comment by RobertCMusk** [comment]
Just released version 1.1.7 with your changes!
