### ISSUE TITLE
need to force window.scrollTo for the startTour to trigger

### ISSUE THREAD

**Issue by MarineMarin** [lsqlabs/ngx-guided-tour#26]
I'd like the walkthrough to open automatically once my page has loaded.
But the first step of the walkthrough only appears on screen if i click anywhere on my page before, which I can't explain.

Though, i can make the walkthrough behave correctly if I force a window.scrollTo(0, y) (y must be > 0 in order for the quick fix to work) just before the call of "this.guidedTourService.startTour(this.shopTour);"

I've been looking for the origin of this issue, but I wasn't successfull. Could you think of some reason this quick fix works for this issue, or even better why this issue happens in the first place?

**Comment by RobertCMusk** [comment]
Is there anything in the browser console?

The main reason I could think of that we have come across is it is trying to start the tour before your content has rendered. If that is true you may be able to wrap the start in a setTimeout with like a 1 second timeout to confirm that is the issue. Most of the places we start our tours we wait until everything is loaded then wait a tick for rendering to be safe.

**Comment by MarineMarin** [comment]
I've put the startTour inside a timeout but the issue is still happening.
I've place a console.log juste before the startTour and another inside the action of the first step and they both appear in the console, but no trace of the first step on screen...

**Comment by RobertCMusk** [comment]
Hmmm, this one is tricky without seeing your code. Are you using OnPush changeDetection anywhere? It sounds like something that may happen because of using OnPush.
If there is anyway you can reproduce it in a shareable format I may be able to help you more.

**Comment by MarineMarin** [comment]
I'll do that asap

**Comment by RobertCMusk** [comment]
Going to close this out since there is no response. Feel free to reopen it if you continue to have issues and you can give us some examples to take a look at.

**Comment by maganap** [comment]
Just to confirm this issue: I had the same problem when trying to start a second tour. The first one worked as expected. The second one only showed up after I clicked on the button with the first target selector.

I had to remove `ChangeDetectionStrategy.OnPush` from the component for it to work, as suggested by @RobertCMusk
