### ISSUE TITLE
[Feature] Make resize message configurable

### ISSUE THREAD

**Issue by lukbdevlab** [lsqlabs/ngx-guided-tour#27]
If you resize your browser below the configured minimium width, the "Please resize" dialog will be shown. The message (title + content) is currently hardcoded:

```
this._guidedTourCurrentStepSubject.next({
  title: 'Please resize',
  content: 'You have resized the tour to a size that is too small to continue. Please resize the browser to a larger size to continue the tour or close the tour.'
});
```

We would like to customize this message to show it in german. The message should be customizable either on the ngx-guided-tour component or as part of the guided tour configuration.

**Comment by RobertCMusk** [comment]
This should be resolved as part of release `1.1.6`.
