### ISSUE TITLE
[Feature] Make progress indicator configurable

### ISSUE THREAD

**Issue by lukbdevlab** [lsqlabs/ngx-guided-tour#28]
The progress indicator shows the current step and total number of steps, e.g "Next 1/5". This indicator is hardcoded in the component template and cannot be customized nor styled as it's not wrapped in any HTML tags.

We would like to show the progress indicator at the top of the tour block and customize it, i.e. "Step 1 of 5".

*Suggested API*
* Add a new input parameter to customize the location of the progress indicator (possible options: inside of next button, at the top of tour block, none)
* Accept a template as input parameter to customize the progress indicator. The two values, the current step and the total number of steps, are provided to this template.

**Comment by lukbdevlab** [comment]
We would like to implement this feature (we'll keep the API backward compatible) and open an PR if that's OK.

**Comment by RobertCMusk** [comment]
This should be resolved as part of release `1.1.6`.
