### ISSUE TITLE
Is bootstrap really a peer dependency?

### ISSUE THREAD

**Issue by philcraven** [lsqlabs/ngx-guided-tour#32]
We are trying to switch to bazel for our build, which is more thorough that the default build. It is insisting that we pull jquery into our app to satisfy a dependency in bootstrap. The need for bootstrap comes from the peer dependency of this project, but when looking over the source I do not see where that dependency comes into play.

**Comment by RobertCMusk** [comment]
We only have `@angular/common` and `@angular/core` listed as peer dependencies projects/ngx-guided-tour/package.json . 

The demo does have bootstrap as a dependency, but understanding is that it should not be pulled in the final released build.

**Comment by RobertCMusk** [comment]
going to close this out since there has  not been any recent activity. Feel free to re open it if you are still seeing this issue with more details.
