### ISSUE TITLE
Problem with "Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by efiloss** [lsqlabs/ngx-guided-tour#40]
Hi, I'm having this error:

![image](https://user-images.githubusercontent.com/6642582/74993747-9c333400-5411-11ea-8787-c14ebe78ceda.png)

Every time I click on "Next" or "Back" buttons, the error is thrown, do you have any advice on this?

Thank you

**Comment by RobertCMusk** [comment]
@efiloss Do you have `<ngx-guided-tour></ngx-guided-tour>` added to your `app.component.html`? That error implies that the step does not exist as an element.

If that is not the solution:
What version are you on?
Can you give me a description of the flow? Does it show the first step then fail? or is it multiple steps in?

**Comment by RobertCMusk** [comment]
going to close this out since there has  not been any recent activity. Feel free to re open it if you are still seeing this issue with more details.
