### ISSUE TITLE
Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by piyush005** [lsqlabs/ngx-guided-tour#46]
I had installed the package using `npm install ngx-guided-tour --save`.
But when i imported the package in app.module

i got this error 
> Initializers are not allowed in ambient contexts.

when i searched on the internet it was found to be an issue of typescript version.
Please help in resolving this issue.

My Project is having following versions:-
"@angular/cli": "~7.0.4",
"typescript": "~2.7.2"

**Comment by RobertCMusk** [comment]
Sorry for taking so long to reply @piyush005 . Are you able to update typescript? Our demo uses typescript 3.5.3 .

We will need to investigate and clarify peerDependencies on typescript before I would be able to give you an exact version, but based I what I see maybe start with version `3.1.1` of typescript if you can upgrade.

**Comment by RobertCMusk** [comment]
Going to close this out if anyone is seeing this problem still feel free to reopen with more details.
