### ISSUE TITLE
Guided tour not visible - Angular 8

### ISSUE THREAD

**Issue by amitgaikwad18** [lsqlabs/ngx-guided-tour#48]
I'm using Angular 8. I have installed ngx-guided-tour and calling it via button click. It is not visible.

here is button click call:

  startTour() {

    this.tourSteps = [{
      title: 'First step',
      content: 'First step content',
      skipStep: true,
    },
    {
      title: 'second step',
      content: 'this is a refresh button',
      skipStep: true,
    }];

    const ngxTour: GuidedTour = {
      tourId: 't1',
      steps: this.tourSteps,
    };

    this.guidedTourService.startTour(ngxTour);

  }

I have added guided-tour-base-theme.scss in angular.json file.

**Comment by chrisd-cotswold** [comment]
Hi,

Have you put <ngx-guided-tour></ngx-guided-tour> into your app.comp.html?

If you don't have this, you won't see anything.

Also, you must have a matching item in the DOM, I note from above that you are missing the selector in the tourStep.

selector:  '.class1',
title: 'Cases total',
content: 'Step 3',
skipStep: false

Finally, both your steps are skipped, so you are going to start the tour and then it's going to complete immediatley.

Hope this helps you out.

Chris

**Comment by amitgaikwad18** [comment]
Hi Chris,

Thanks.

I think the culprit was skipStep = true.

One more question, I'm using ID selector. and it is unable to find it in DOM. Does ID selector work? or it has to be CLASS selector.

Regards,
Amit

**Comment by amitgaikwad18** [comment]
Hi Chris,

Solved it by adding # for ID selector:

{
      selector: '#btnRefresh',
      title: 'second step',
      content: 'this is a refresh button',
      skipStep: false,
    }

Thanks a lot for your help.

Cheers,
Amit
