### ISSUE TITLE
Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by Chris1234567899** [lsqlabs/ngx-guided-tour#50]
I'm receiving this error:

```
core.js:6014 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at GuidedTourComponent.getStepScreenAdjustment (ngx-guided-tour.js:824)
```
Apparently this line 
```
 /** @type {?} */
        const tourStepHeight = typeof this.tourStep.nativeElement.getBoundingClientRect === 'function' ? this.tourStep.nativeElement.getBoundingClientRect().height : 0;
```
is causing the error.

It just throws the error in the console but the tour is displayed without any notable issues either way.

I'm using it with angular 8 and ionic 5 in a lazy loading module if that is of importance (I added both the <ngx-guided-tour> tag and the module imports and providers in the lazy loaded module, not the app.module).

**Comment by RobertCMusk** [comment]
@Chris1234567899 did you add `<ngx-guided-tour></ngx-guided-tour>` to you app-component.html?

**Comment by Chris1234567899** [comment]
Thanks, I had the tag it in the lazy loaded component, but after adding it (once for the whole app) in app.components, I don't get the error anymore. 
I thought controlling the tour through the service had to be in the same component like the <ngx-guided-tour></ngx-guided-tour>, but that is luckily not the case.
