### ISSUE TITLE
Angular 9 compiler warning ngx-guided-tour

### ISSUE THREAD

**Issue by SaifJerbi** [lsqlabs/ngx-guided-tour#51]
After upgrading to Angular 9, we get the warning below 
```
Entry point 'ngx-guided-tour' contains deep imports into 'PATH/node_modules/rxjs/internal/operators', 'PATH/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

**Comment by RobertCMusk** [comment]
@SaifJerbi version 1.1.9 was released with your change. Thank you for contributing!

**Comment by SaifJerbi** [comment]
Hi @RobertCMusk, unfortunately i missed an import in my PR so the warning is stil there
[import to be removed](https://github.com/lsqlabs/ngx-guided-tour/blob/7290ac88622a5b7732299499ec8befb663e16a47/projects/ngx-guided-tour/src/lib/guided-tour.service.ts#L1)
I will reopen this issue and add a new PR
