### ISSUE TITLE
How and where do we use this please? -> ngx-guided-tour component inputs

### ISSUE THREAD

**Issue by prameshbajra** [lsqlabs/ngx-guided-tour#73]
Reference Link: https://github.com/lsqlabs/ngx-guided-tour#ngx-guided-tour-component-inputs

Can you please add to the readme (or answer here - I will create a readme and raise a pull request) on how to use this to change the text of the skip button?

I am new to `ngx-guided-tour` and I am having a difficult time figuring this out.

Thanks. Appreciate your time.

**Comment by RobertCMusk** [comment]
It is in the `ngx-guided-tour component inputs` section ngx-guided-tour component inputs as the property `skipText` so when you add `<ngx-guided-tour>` you can add a property with your skip text.

**Comment by prameshbajra** [comment]
> It is in the `ngx-guided-tour component inputs` section (https://github.com/lsqlabs/ngx-guided-tour#ngx-guided-tour-component-inputs) component inputs as the property `skipText` so when you add `<ngx-guided-tour>` you can add a property with your skip text.

I'm so sorry. I'm an idiot. Can you please elaborate?
Or may be an example? I still do not get it.

Thank you.

**Comment by RobertCMusk** [comment]
so `<ngx-guided-tour skipText="new skip text"></ngx-guided-tour>` where you you put `<ngx-guided-tour></ngx-guided-tour>` should do what you are asking for. If you look at those docs there is a couple other text properties if you need them too.

**Comment by prameshbajra** [comment]
> so `<ngx-guided-tour skipText="new skip text"></ngx-guided-tour>` where you you put `<ngx-guided-tour></ngx-guided-tour>` should do what you are asking for. If you look at those docs there is a couple other text properties if you need them too.

Thank you so much.
Can't believe, out of all those things I tried. It was this simple. :/
