### ISSUE TITLE
Able to access backgronud controls when tour is open

### ISSUE THREAD

**Issue by PankajM575** [lsqlabs/ngx-guided-tour#74]
We have implemenetd guided tour in our app, but when we tour is running the background controls on page are accessible.
In demo link also, restart tour button is accessible. https://lsqlabs.github.io/ngx-guided-tour/

**Comment by RobertCMusk** [comment]
@PankajM575 Which browser are you using? I am unable to reproduce in the demo using Chrome.

**Comment by PankajM575** [comment]
Its resolved now. We used preventBackdropFromAdvancing:true
